---
title: "Module: Real World Research Using FHIR"

area:
  name: Overview
topic:
  name: FHIR for Research

roles:
  - Investigator
  - Research Leaders
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

learning_objectives:
  - question: How have researchers used FHIR in the past?
    answer: Researchers have used FHIR to transform data between common data models, engage and communicate with study participants, and facilitate multi-site collaboration.
  - question: What data formats and resources have researchers used with FHIR?
    answer: Researchers have used data models like OMOP, PCORnet; platforms like openEHR, REDCap, Apple ResearchKit; and frameworks like SMART on FHIR in studies alongside FHIR.
---

A review of studies that use FHIR in their research, including a meta-analysis of papers on FHIR for research [@duda2022], found four themes that could be adapted to other health centers or projects:

- Data models and platforms
- SMART on FHIR
- Patient-facing apps
- Multi-site research

## Data models and platforms

In several studies, researchers used FHIR to transform health data from incompatible data models into a single format. Compatibility challenges are common for studies that use data from different sources.
<!-- DISCUSS this section would benefit from a really high level description of OMOP vs FHIR. Maybe we are assuming the audience already knows OMOP well? I don't, and I'm finding this section confusing, particularly why I would want to use FHIR and OMOP together. --LDC -->

<strong>@Lenert_2021</strong> describes a method of using FHIR to consolidate COVID-19 data from multiple institutions, and then distributing the data to [PCORnet](https://pcornet.org/) and [OMOP](https://www.ohdsi.org/data-standardization/) for analysis ([more on Common Data Models (CDMs)](cdms.qmd)). The authors describe this method as the "best of both worlds" because FHIR helps represent clinical events, while PCORnet and OMOP help compute and analyze clinical events.

Using FHIR as the base data standard and converting FHIR to other CDMs shortened the timeline from data acquisition to analysis. A shorter timeline was critical for an emerging pandemic like COVID-19 and could be helpful for other rapidly changing clinical research.

<strong>@Wood_2021</strong> offers another example of using both OMOP and FHIR. @Wood_2021 uses OMOP and FHIR to create disease-specific learning communities from real-world data. Using both data models reduces burden and ensures sustainability for the learning community by routinely ingesting patients' entire corpus of EHR data. Working with both data standards also opens participation to more data sources like health care systems, hospitals, and outpatient practices, that already use OMOP or FHIR.
<!-- DISCUSS I don't understand this para very well. I suggest reworking it.
.
Why does using *both* reduce burden? Is this saying using OMOP and FHIR instead of *other* or *more* data standards? Or is it saying using them together vs one or the other?  
.
Why does it ensure sustainability? What does sustainability mean in this context? How does ingesting the "entire corpus" ensure sustainability?
.
"Working with both data standards also opens participation..." - vs just FHIR or just OMOP? Or vs other data standards? The more standards you support, the more health systems... but that gets unwieldy. Does this need something to say most health care systems use either OMOP or FHIR?--LDC -->

<strong>@Rinaldi_Thun_2021</strong> mapped openEHR information to FHIR, and then to OMOP. The process combined data from eight university hospitals in Germany to create an infection surveillance consortium<!-- FIX: what is an infection surveillance consortium? Is the consortium people? institutions? an application/database? Currently phrased as though it's an application/database (or similar) made from all the data, but I don't think that's it. Suggest rephrasing this sentence to clarify --LDC --> with <!--FIX: "with access to rapidly..."? Not sure if this works better in this context. --LDC -->rapidly updating information. The group planned to use [openEHR](https://openehr.org/) to model infection-related information, but also wanted to conform to the [Medical Informatics Initiative (MII)](https://www.medizininformatik-initiative.de/en/start), which requires member organizations to use FHIR. However, the consortium wanted a population-level perspective, but FHIR is designed to support patient-level data. They found that OMOP provided a broader view of the data and the analytic capabilities they needed. Transforming the data through the three models--openEHR, FHIR, and OMOP--let them use the benefits of each while keeping interoperability between the hospitals and the MII.

```{=html}
<!--# DISCUSS:
Including one or both of the examples below from Rinaldi & Thun 2021 might be illustrative but will need to reformat. Happy to remove if they aren't useful
 --KMB -->
```
![Example of the cultures studied and mapping from openEHR, to FHIR, and then OMOP. [@Rinaldi_Thun_2021]](images/rinaldi-culture-mapping.png)

![Example of mapping resources from openEHR, to FHIR, and then OMOP. [@Rinaldi_Thun_2021]](images/rinaldi-openehr-fhir-omop-mappings.png)

## SMART on FHIR

[SMART on FHIR](https://smarthealthit.org/about-smart-2/) is an application programming interface (API) that enables interoperability between system with FHIR endpoints. A widely used SMART on FHIR implementation is the Apple Health Records API, which allows iPhone users to request records from EHRs and other health systems and store the information on their iPhone.

SMART has an [app gallery](https://apps.smarthealthit.org/apps?sort=name-asc) for viewing applications that can be implemented in an EHR.

<strong>@Wagholikar_2017</strong> trialed sharing SMART on FHIR apps at Partners Healthcare (PHC) in Boston, Massachusetts and REACHnet Data Center (RDC) in New Orleans, Louisiana. They imported EHR data from the two institutions into Patient-Centered Outcomes Research Institute's (PCORI)<!-- FIX: is this PCORNet? Should this acronym spell out be above where PCORNet is first used? --LDC --> CDM and stored the EHR data in Informatics for Integrating Biology and the Bedside ([i2b2](https://www.i2b2.org/)) repositories.

![The proposed model for using SMART on FHIR to collaborate across institutions and their respective EHRs. [@Wagholikar_2017]](images/wagholikar-proposed-approach.png)

They used SMART on FHIR to transform from the PCORnet CDM to FHIR. Once the data was in the FHIR format, the authors tested four SMART apps from the app gallery.

![The data pipeline used to move data from EHRs to SMART apps. [@Wagholikar_2017]](images/wagholikar-pipline.png)

At PHC, the pipeline ran smoothly, and all data was accounted for in the SMART apps. At RCD, the pipeline also ran smoothly, apart from a cardiac-risk SMART app that signaled missing data. Further investigation revealed that the SMART on FHIR platform could not support the complex query used in certain FHIR resources.

Despite the limitation for certain FHIR resources, the SMART on FHIR framework and apps can be used to share research infrastructure and collaborate across institutions. SMART apps can integrate with different EHRs, removing many interoperability barriers.

## Patient-facing apps

FHIR can also be used to create interoperable, patient-facing apps that collect data or enable researcher-participant messaging. Some apps listed in the [SMART app gallery](https://apps.smarthealthit.org/apps?sort=name-asc) linked above are patient-facing apps.

<strong>@Pfiffner_2016</strong> created an extension called Consent, Contact, and Community framework for Patient Reported Outcomes (C3-PRO) that connects [Apple's ResearchKit](https://developer.apple.com/researchkit/) to health systems. The open-source tool uses FHIR to connect the Apple ResearchKit app to the i2b2 standard. They found that FHIR formats standardized the survey questions and consent libraries for study participation. Because they were standardized, they could be used in other studies.
<!-- FIX: does Apple ResearchKit use FHIR? If so, make it explicit. --LDC -->

The initial test case for C3-PRO, also described in @Pfiffner_2016, was to enroll an anonymous cohort in a study using data from i2b2. Participants used an app to track and report their symptoms of Hepatitis C. 

C3-PRO can help in other studies, using FHIR to determine participant eligibility, format informed consent documents, and generate the study surveys.

<strong>@Ahmad_2020</strong> uses [REDCap](redcap-intro.qmd) to program surveys, and Apple ResearchKit to render and deliver them in a user-friendly format. The responses are then sent<!-- make active voice - what sends back the response? ResearchKit? A different app? --LDC --> back to REDCap and a proprietary program<!-- what program? Name it --LDC --> that converts the data into an [HL7 V2 message](https://en.wikipedia.org/wiki/Health_Level_7#Version_2_messaging). The V2 message is added to the patient's EHR data.[^1] A clinical decision support (CDS) tool then suggests tests based on the responses.

The survey was given to 15-21-year-old ER patients to determine what tests for sexually transmitted infections (STIs) were appropriate. Despite the potentially sensitive subject matter, 88.9% of the patients surveyed said answering the questions electronically was "somewhat comfortable" or "very comfortable," and 72.2% preferred a digital survey over a face-to-face conversation or paper survey.

[^1]: V2 could in theory be replaced by FHIR, which is typically easier for software developers and informaticists to work with than V2.

## Multi-site research

Using large pools of data from multiple healthcare institutions supports more comprehensive studies with broader participant bases. However, multi-site data-sharing requires standardized formats and common terminologies. FHIR helps researchers establish these.

When starting the design of a study, researchers determine the size of the patient population that can participate in the study or will be impacted by the study. However, if researchers can only query patient records from their local institution, they may not have a complete picture of the patient population of interest. @Gruendner_2022 eliminated this barrier by designing a query that works across multiple health centers in Germany. The query process involved four components:

1.  User-interface for writing queries
2.  Backend for translating the user input to a standardized format
3.  Middleware to transport the query
4.  Execution service to convert the standardized query to FHIR

For the query to work, all participating institutions had to share a common ontology and terminology mappings. The authors tested their feasibility query with 33 university hospitals in Germany, using synthetic data containing millions of FHIR resources. The feasibility query returned the number of patients that match the requested criteria within seconds. The authors note that they could easily tweak the returned value to be patient IDs to create a cohort.

## Other references

Below is a list of studies that used FHIR in some capacity. These may be helpful for generating ideas of how FHIR could benefit your research:

-   Data Models
    -   @Lambarki_2021
    -   @Jiang_2017a
    -   @Fischer_2020
    -   @Pfaff_2019
    -   @Jiang_2017b
-   SMART on FHIR
    -   @Mandel_Kreda_Mandl_Kohane_Ramoni_2016

    -   @Bloomfield_Polo-Wood_Mandel_Mandl_2017

    -   @Jones_Gottlieb_Mandel_Ignatov_Ellis_Kubick_Mandl_2021

        @Wesley_Blumenthal_Shah_Littlejohn_Pruitt_Dixit_Hsiao_Dymek_Ratwani_2021

    -   @Sayeed_Gottlieb_Mandl_2020
-   Patient-Facing Apps
    -   @Pawelek_Baca-Motes_Pandit_Berk_Ramos_2022
    -   @Bartschke_Börner_Thun_2021
    -   @Burkhardt_Brandt_Lee_Karras_Bugni_Cvitkovic_Chen_Lober_2021
    -   @Ploner_Prokosch_2020
-   Multi-site Research
    -   @Garza_2020
-   Meta-Analysis on FHIR for Research
    -   @Vorisek_Lehne_Klopfenstein_Mayer_Bartschke_Haese_Thun_2022
    -   @Griffin_2022
-   REDCap
    -   @Metke-Jimenez_Hansen_2019
-   Cohort Building
    -   @Gruendner_Gulden_Kampf_Mate_Prokosch_Zierk_2021
    -   @Bradshaw_2022
-   Terminologies
    -   @Chatterjee_Pahari_Prinz_2022
-   FAIR Data
    -   @Sinaci_Nunez_2020
-   SDOH
    -   @Watkins_Viernes_Nguyen_Rojas_Mezarina_Silva_Valencia_Borbolla_2020
-   Adverse Event Reporting
    -   @Wang_Lehmann_Botsis_2021
-   Software Dev
    -   @Hong_Prodduturi_Wang_Jiang_2017
-   Environmental Health
    -   @Xu_Cox_Stillwell_Pfaff_Champion_Ahalt_Fecho_2020
-   CDS/SMART
    -   @Jung_Bae_Seong_Oh_Kim_Yi_2022
