const role_module_map = [
  {
    "role": "clinician-scientist",
    "modules": [
        {"slug": "smart-on-fhir-research",              "text": "SMART on FHIR for Research"},
        {"slug": "terminology",                         "text": "Terminology"},
        {"slug": "redcap-best-practices",               "text": "REDCap Best Practices"},
        {"slug": "tabular-retrieving-and-subsetting",   "text": "Tabular Data: Retrieving and Subsetting"},
        {"slug": "redcap-example",                      "text": "REDCap Examples"},
        {"slug": "key-fhir-resources",                  "text": "Key FHIR Resources"},
        {"slug": "fhir-history",                        "text": "History of FHIR"},
        {"slug": "smart-on-fhir-intro",                 "text": "Introduction to SMART on FHIR"},
        {"slug": "cdms",                                "text": "Common Data Models"},
        {"slug": "fhir-research",                       "text": "FHIR for Research"},
        {"slug": "data-modeling-real-world-igs",        "text": "Data Modeling: Real World IGs"},
        {"slug": "fhir-from-10000-ft",                  "text": "FHIR from 10,000ft"},
        {"slug": "smart-on-fhir-technical-quick-start", "text": "SMART on FHIR Technical Quickstart"},
        {"slug": "redcap-intro",                        "text": "Introduction to REDCap"},
        {"slug": "data-modeling-api-resources",         "text": "Data Modeling: API Resources"},
        {"slug": "tabular-from-fhir",                   "text": "Tabular Data: to and from FHIR"},
        {"slug": "data-modeling-reading-igs",           "text": "Data Modeling: Reading IGs"},
        {"slug": "example-study",                       "text": "Examples of Real World Studies"},
        {"slug": "data-modeling-writing-igs",           "text": "Data Modeling: Writing IGs"},
        {"slug": "tabular-real-world",                  "text": "Tabular Data: Real World Cases"}
    ]
  },
  {
    "role": "informaticist",
    "modules": [
        {"slug": "smart-on-fhir-research",              "text": "SMART on FHIR for Research"},
        {"slug": "terminology",                         "text": "Terminology"},
        {"slug": "redcap-best-practices",               "text": "REDCap Best Practices"},
        {"slug": "tabular-retrieving-and-subsetting",   "text": "Tabular Data: Retrieving and Subsetting"},
        {"slug": "redcap-example",                      "text": "REDCap Examples"},
        {"slug": "key-fhir-resources",                  "text": "Key FHIR Resources"},
        {"slug": "fhir-history",                        "text": "History of FHIR"},
        {"slug": "smart-on-fhir-intro",                 "text": "Introduction to SMART on FHIR"},
        {"slug": "cdms",                                "text": "Common Data Models"},
        {"slug": "fhir-community",                      "text": "FHIR Community"},
        {"slug": "fhir-research",                       "text": "FHIR for Research"},
        {"slug": "data-modeling-real-world-igs",        "text": "Data Modeling: Real World IGs"},
        {"slug": "fhir-from-10000-ft",                  "text": "FHIR from 10,000 Feet"},
        {"slug": "smart-on-fhir-technical-quick-start", "text": "SMART on FHIR Technical Quickstart"},
        {"slug": "redcap-intro",                        "text": "Introducion to REDCap"},
        {"slug": "data-modeling-api-resources",         "text": "Data Modeling: API Resources"},
        {"slug": "tabular-from-fhir",                   "text": "Tabular Data: to and from FHIR"},
        {"slug": "data-modeling-reading-igs",           "text": "Data Modeling: Reading IGs"},
        {"slug": "example-study",                       "text": "Examples of Real World Studies"},
        {"slug": "data-modeling-writing-igs",           "text": "Data Modeling: Writing IGs"},
        {"slug": "tabular-real-world",                  "text": "Tabular Data: Real World Cases"}
    ]
  },
  {
    "role": "investigator",
    "modules": [
        {"slug": "smart-on-fhir-research",              "text": "SMART on FHIR for Research"},
        {"slug": "terminology",                         "text": "Terminology"},
        {"slug": "redcap-best-practices",               "text": "REDCap Best Practices"},
        {"slug": "tabular-retrieving-and-subsetting",   "text": "Tabular Data: Retrieving and Subsetting"},
        {"slug": "redcap-example",                      "text": "REDCap Examples"},
        {"slug": "fhir-history",                        "text": "History of FHIR"},
        {"slug": "smart-on-fhir-intro",                 "text": "Introduction to SMART on FHIR"},
        {"slug": "cdms",                                "text": "Common Data Models"},
        {"slug": "fhir-research",                       "text": "FHIR for Research"},
        {"slug": "data-modeling-real-world-igs",        "text": "Data Modeling: Real World IGs"},
        {"slug": "fhir-from-10000-ft",                  "text": "FHIR from 10,000 Feet"},
        {"slug": "smart-on-fhir-technical-quick-start", "text": "SMART on FHIR Technical Quickstart"},
        {"slug": "redcap-intro",                        "text": "Introducion to REDCap"},
        {"slug": "data-modeling-api-resources",         "text": "Data Modeling: API Resources"},
        {"slug": "tabular-from-fhir",                   "text": "Tabular Data: to and from FHIR"},
        {"slug": "data-modeling-reading-igs",           "text": "Data Modeling: Reading IGs"},
        {"slug": "example-study",                       "text": "Examples of Real World Studies"},
        {"slug": "data-modeling-writing-igs",           "text": "Data Modeling: Writing IGs"},
        {"slug": "tabular-real-world",                  "text": "Tabular Data: Real World Cases"}
    ]
  },
  {
    "role": "research-leader",
    "modules": [
        {"slug": "smart-on-fhir-research",              "text": "SMART on FHIR for Research"},
        {"slug": "redcap-best-practices",               "text": "REDCap Best Practices"},
        {"slug": "tabular-retrieving-and-subsetting",   "text": "Tabular Data: Retrieving and Subsetting"},
        {"slug": "redcap-example",                      "text": "REDCap Examples"},
        {"slug": "fhir-history",                        "text": "History of FHIR"},
        {"slug": "smart-on-fhir-intro",                 "text": "Introduction to SMART on FHIR"},
        {"slug": "cdms",                                "text": "Common Data Models"},
        {"slug": "fhir-research",                       "text": "FHIR for Research"},
        {"slug": "data-modeling-real-world-igs",        "text": "Data Modeling: Real World IGs"},
        {"slug": "fhir-from-10000-ft",                  "text": "FHIR from 10,000 Feet"},
        {"slug": "smart-on-fhir-technical-quick-start", "text": "SMART on FHIR Technical Quickstart"},
        {"slug": "redcap-intro",                        "text": "Introducion to REDCap"},
        {"slug": "data-modeling-api-resources",         "text": "Data Modeling: API Resources"},
        {"slug": "tabular-from-fhir",                   "text": "Tabular Data: to and from FHIR"},
        {"slug": "example-study",                       "text": "Examples of Real World Studies"},
        {"slug": "data-modeling-writing-igs",           "text": "Data Modeling: Writing IGs"},
    ]
  },
  {
    "role": "software-engineer",
    "modules": [
        {"slug": "smart-on-fhir-research",              "text": "SMART on FHIR for Research"},
        {"slug": "terminology",                         "text": "Terminology"},
        {"slug": "redcap-best-practices",               "text": "REDCap Best Practices"},
        {"slug": "tabular-retrieving-and-subsetting",   "text": "Tabular Data: Retrieving and Subsetting"},
        {"slug": "redcap-example",                      "text": "REDCap Examples"},
        {"slug": "key-fhir-resources",                  "text": "Key FHIR Resources"},
        {"slug": "fhir-history",                        "text": "History of FHIR"},
        {"slug": "smart-on-fhir-intro",                 "text": "Introduction to SMART on FHIR"},
        {"slug": "cdms",                                "text": "Common Data Models"},
        {"slug": "fhir-community",                      "text": "FHIR Community"},
        {"slug": "fhir-research",                       "text": "FHIR for Research"},
        {"slug": "data-modeling-real-world-igs",        "text": "Data Modeling: Real World IGs"},
        {"slug": "fhir-from-10000-ft",                  "text": "FHIR from 10,000ft"},
        {"slug": "smart-on-fhir-technical-quick-start", "text": "SMART on FHIR Technical Quickstart"},
        {"slug": "redcap-intro",                        "text": "Introduction to REDCap"},
        {"slug": "data-modeling-api-resources",         "text": "Data Modeling: API Resources"},
        {"slug": "tabular-from-fhir",                   "text": "Tabular Data: to and from FHIR"},
        {"slug": "data-modeling-reading-igs",           "text": "Data Modeling: Reading IGs"},
        {"slug": "example-study",                       "text": "Examples of Real World Studies"},
        {"slug": "data-modeling-writing-igs",           "text": "Data Modeling: Writing IGs"},
        {"slug": "tabular-real-world",                  "text": "Tabular Data: Real World Cases"}
    ]
  }
];
