---
title: "Real World Example"

area:
  name: FHIR Data
topic:
  name: REDCap

roles:
  - Investigator
  - Research Leaders
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

learning_objectives:
  - question: What is REDCap? 
    answer: REDCap is a HIPAA-compliant survey tool that can be used to collect data from patients, gather information on study participants, and population registries.
  - question: How does a REDCap administrator support REDCap users?
    answer: REDCap administrators serve a critical role in the REDCap adoption process at an institution. They are a go-to resource for any questions related to the platform.
---

<!-- DISCUSS: I'm confused about the purpose of this module. I would think it would be a real-world example of *FHIR* being used with REDCap.

However, it seems to be an intro to REDCap (wouldn't this be in the redcap-intro section?), and an example of REDCap being used.

I think you can remove most of this, refer people back to the intro module for intro stuff, and expand on section 2: "Examples of REDCap with FHIR".

--LDC
-->

## Introduction

#### What is REDCap

Research Electronic Data Capture (REDCap) is a HIPAA-compliant survey tool. It was designed in 2004 by researchers at Vanderbilt University that needed to capture personal health information in a secure and reliable format [@About_REDCap]. Since then, REDCap has grown into a global community with 3200 partner institutions in 128 countries and more than 56,000 projects [@Harris_Taylor_Minor_Elliott_Fernandez_ONeal_McLeod_Delacqua_Delacqua_Kirby_etal._2019]. 


FHIR can be used with REDCap to facilitate data exchange, particularly if researchers want to utilize information that is already captured in an electronic health record (EHR). Within the United States and Canada, 40 institutions have integrated REDCap with their Epic or Cerner EHR [@Cheng_Banasiewicz_Johnson_Sulieman_Kennedy_Delacqua_Lewis_Joly_Bistran-Hall_Collins_2023].

#### What can REDCap be used for?

REDCap can be used for several research-related objectives:

-   collecting standard sets of information for study participation
-   maintaining and updating population health registries
-   automating the completion of Case Report Forms (CRFs) from electronic health records (EHRs)


<!--# Would it make sense to link to the FHIR-real-world-research page that has summaries on FHIR and REDCap papers? Or should that content be moved here? -- kmb -->

<!--# The following two paragraphs that I commented out are also in the REDCap intro module. Was that intentional? -- kmb -->

<!--#[REDCap](https://www.project-redcap.org) (which stands for "Research Electronic Data Capture") is another useful, FHIR-compatible tool. @Cheng_2021 describe the development of the Clinical Data Interoperability Services (CDIS), which facilitates the exchange of data between REDCap and any EHR via the FHIR API. The authors tested two use cases for CDIS: Clinical Data Pull (CDP) and Clinical Data Mart (CDM).

The CDP use case would apply to prospective studies that aggregate data and fill out case report forms (CRFs) for study participants. The CDM use case is for studies with a known cohort of patients and requires a bulk data extraction from an EHR. At the time of publishing, 55 CDP projects and 27 CDM projects had been implemented. Both use cases significantly reduced manual data entry into REDCap. CDIS has also proven to be reusable between projects at an institution, without the need for support from IT staff.

![The CDIS workflow uses FHIR to simplify the process of creating a registry from EHR data. [@Cheng_2021]](images/cheng-fhir-shortcut.png) -->

## Examples of REDCap with FHIR

#### REDCap as a registry

Lenert et al. (2023) [@Lenert_Jacobs_Agnew_Ding_Kirchoff_Weatherston_Deans_2023] tested a population-level vaccination status tracker, called VACtrac, using a combination of two approaches:

1. A FHIR-compatible copy of the existing statewide Immunization Information System (IIS), with a REDCap data warehouse
2. A REDCap health management program with a list of patients for providers to maintain communication with and update vaccination status records, either through a Bulk FHIR update or one-time query.

VACtrac uses REDCap Clinical Data Interoperability Services (CDIS) FHIR plug-in for both Epic and Cerner EHRs to extract patient information. The REDCap database can be accessed and updated by multiple providers, so the burden of maintaining vaccination information can be spread among multiple providers.

The [REDCap vaccination status tracker](https://github.com/vactraccovid/vactrac) is publicly available for adaption in other institutions.

#### Transforming REDCap data to FHIR resources

Metke-Jimenez & Hansen (2019) [@Metke-Jimenez_Hansen_2019] implemented FHIRCap, a transformation engine, to translate data in a REDCap project to FHIR resources. The authors tested FHIRCap on an existing REDCap form and database for a cancer registry. They were able to transform the information from REDCap to FHIR resources and then map the codes to SNOMED CT. While the process was manual and time intensive to set up, the rules only have to be written once for a project and can be used as long as the REDCap form doesn't change.

FHIR and REDCap can also be used together to automate the process of population case report forms (CRFs), which could increase accuracy and decrease the burden of manual data entry. Cheng et al. (2023) [@Cheng_Banasiewicz_Johnson_Sulieman_Kennedy_Delacqua_Lewis_Joly_Bistran-Hall_Collins_2023] tested this hypothesis with an existing project that required manual data collecting and entry from EHRs to CRFs. The process was not FHIR compatible at the time, so it served as a baseline to compare their automated process of the same data against.

## REDCap Adoption 

<!-- DISCUSS: what is the purpose of this section? it doesn't talk about fhir at all. Do we want a general "redcap is being used"? or a more specific "redcap with fhir is being used"? If the former, why? If the latter, the use cases below should be changed to include fhir. --LDC -->
Hawley et al. (2021) [@Hawley_Yu_Bogetic_Potapova_Wakefield_Thompson_Kloiber_Hill_Jankowicz_Rotenberg_2021] describes a usability and implementation study at the Centre for Addiction and Mental Health (CAMH) in which they used REDCap to capture self-assessments from patients and transfer the data into a Cerner EHR. When a patient arrived the process saved time, improved the accuracy of data going into the EHR, and made the data accessible in real-time. Hawley et al. (2021) also identified useful roles and responsibilities for implementing REDCap:

<!-- DISCUSS: I think this can just be a list of roles w/o the explanations and link to the source for the explanations. --LDC -->
> -   **Clinical REDCap administrator**: Clinical REDCap staff responsible for account creation, modification, and suspension for all user types. Responsible for moving projects and draft changes to production. Limited to 2-3 staff members.
> -   **Project developer administrator**: Clinical REDCap staff responsible for creating REDCap projects and associated forms or surveys. Leads project validation to be carried out in collaboration with clinical stakeholders.
> -   **Service administrator**: Specialized account for managing secure services post data collection (e.g., application programming interface data export to electronic health record).
> -   **Clinical data lead**: Clinical staff responsible for monitoring the integrity of the data, providing clinic-specific training to clinic users, supporting minor technical issues in the clinic, facilitating project validation, submitting project change requests, approving subordinate account requests, and serving as the main point of contact for developers and administrators.
> -   **Clinical care provider**: Clinical staff responsible for the administration and review of clinical assessments; can enter data that have been collected on paper into REDCap.
> -   **Clinical assistant**: Clinical support staff responsible for administering patient survey queue in the clinic and providing simple technical assistance.

Another study that focused on the adoption of REDCap in academic and clinical environments identified similar roles and strategies to facilitate the process (Mare et al. 2022). They identified the following methods to support new REDCap users:

>-   top-down organizational support; 
>-   secure and reliable application, hosting infrastructure, and systems administration; an enabling and accessible REDCap support team; 
>-   regular hands-on training workshops covering REDCap project setup and data collection instrument design techniques; 
>-   annual local symposia to promote networking and awareness of all the latest software features and best practices for using them; 
>-   participation in REDCap Consortium activities; 
>-   and regular and ongoing mentorship from members of the Vanderbilt University Medical Center (Mare et al. 2022).

The authors also used two strategies to support adoption of REDCap: 
1. Building trust among researchers in the security and reliability of REDCap through several layers of back-up should any component fail and simulated data loss and retrieval exercises.
2. Establishing a REDCap administrator that acted as a dedicated, go-to person that could answer researchers' questions and offer consultations.

## Conclusion

REDCap and FHIR have global communities of users with an array of resources and forums for user support. 

-   More on the REDCap community <!--# Some of REDCap resources are going to be institutionally-based but given conversation with Will, maybe we consider a brief REDCap community module? Or add something here on REDCap community? --><!-- needs link --LDC -->
-   [More on the FHIR community](fhir-community.qmd)

When used together, FHIR can help researchers using REDCap to streamline their data collection and storage processes, find study participants, and develop study cohorts with greater accuracy.