# gitlab-ci.yml

image: registry.gitlab.com/quarto-forge/docker/polyglot

before_script:
  - quarto check

workflow:
  rules:
    # trigger every commit
    - if: $CI_COMMIT_BRANCH

pages:
  stage: deploy
  script:
    - quarto render .
  artifacts:
    paths:
      - public
  rules:
    # Only run for default branch
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  tags:
    - pages
  environment: production

ci:
  stage: deploy
  artifacts:
    paths:
      - public
    expire_in: 6 months

  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: https://${CI_PROJECT_NAMESPACE}.pages.mitre.org/-/${CI_PROJECT_NAME}/-/jobs/$CI_JOB_ID/artifacts/public/index.html

  script:
    - quarto render . --site-url https://${CI_PROJECT_NAMESPACE}.pages.mitre.org/-/${CI_PROJECT_NAME}/-/jobs/$CI_JOB_ID/artifacts/public/

  tags:
    - pages
  rules:
    # Do not run for the default branch, which is published via the `pages` pipeline defined above
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$CI_COMMIT_BRANCH' # Necessary to have a catch-all match to make the pipeline run

