project:
  type: website
  output-dir: public
  render:
    - "!cache/" # naming this _cache should work instead, but did not in testing https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2

website:
  title: "FHIR for Research"
  site-url: https://fhir-for-research.pages.mitre.org/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - r_demo.qmd
      - python_demo.qmd
  page-footer:
    center:
      - text: "&copy; MITRE 2022"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



