project:
  type: website
  output-dir: public
  render:
    - "*.qmd"
    - "!cache/" # naming this _cache should work instead, but did not in testing https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2
    - "!README.md"

website:
  title: "FHIR for Research"
  site-url: https://fhir-for-research.pages.mitre.org/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - r_demo.qmd
      - python_demo.qmd
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - units/01-fhir-intro.qmd
      
  page-footer:
    center:
      - text: "&copy; MITRE 2023"
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: head.html
    include-after-body: scripts.html


