project:
  type: website
  output-dir: public

website:
  title: "FHIR for Research"
  site-url: https://fhir-for-research.pages.mitre.org/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - r_demo.qmd
  page-footer:
    center:
      - text: "&copy; MITRE 2022"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



