project:
  type: website
  output-dir: public
  render:
    - "*.qmd"
    - "!cache/" # naming this _cache should work instead, but did not in testing https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2
    - "!README.md"

website:
  title: "FHIR for Research"
  site-url: https://fhir-for-research.pages.mitre.org/
  navbar:
    left:
      - text: Overview
        file: sections/overview.qmd
      - text: Working With Data
        file: sections/working-with-data.qmd
      - text: Advanced Topics
        file: sections/advanced-topics.qmd


    right:
      - href: contribute.qmd
        text: Contributions & Corrections
      - icon: github
        href: https://github.com/mitre/

  sidebar:
    - id: overview
      title: Overview
      style: floating
      search: false
      align: left
      collapse-level: 1
      contents:
        - section: "FHIR for Research"
          contents:
            - modules/fhir-from-10000-ft.qmd
            - modules/fhir-from-1000-ft.qmd
            - file: modules/10-intro--real-world-research-using-fhir/index.qmd
              text: "Real World Research"
            - modules/10-intro--key-fhir-resources/index.qmd
            - modules/10-intro--accessing-fhir-data/index.qmd
            - file: modules/10-intro--brief-history-of-fhir/index.qmd
              text: "History of FHIR"
            - modules/10-intro--terminology-introduction/index.qmd
            - modules/10-intro--common-data-models-and-fhir/index.qmd
            - file: modules/10-intro--fhir-community-and-resources/index.qmd
              text: Community & Documentation
        - section: "SMART on FHIR"
          contents:
            - modules/20-intro-smart-on-fhir--overview/index.qmd
            - modules/20-intro-smart-on-fhir--real-world-research/index.qmd
            - modules/20-intro-smart-on-fhir--technical-quick-start/index.qmd


  page-footer:
    center:
      - text: Footer text goes here



format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    include-in-header: head.html
    include-after-body: scripts.html
