project:
  type: website

website:
  title: "FHIR for Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: r_demo.qmd
        text: "R Demo"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



