project:
  type: website
  output-dir: public
  render:
    - "*.qmd"
    - "!cache/" # naming this _cache should work instead, but did not in testing https://community.rstudio.com/t/quarto-equivalent-to-exclude-yaml-command-in-distill/148758/2
    - "!README.md"
    - "!script/"

website:
  title: "FHIR for Research"
  site-url: https://mitre.github.io/fhir-for-research/
  navbar:
    left:
      - text: Overview
        file: sections/overview.qmd
      - text: Working With Data
        file: sections/working-with-data.qmd
      - text: Advanced Topics
        file: sections/advanced-topics.qmd


    right:
      - href: contribute.qmd
        text: Contributions & Corrections
      - icon: github
        href: https://github.com/mitre/fhir-for-research

  sidebar:
    - id: overview
      title: Overview
      style: floating
      search: false
      align: left
      collapse-level: 2
      contents:
        - sections/overview.qmd
        - section: "FHIR for Research"
          contents:
            - modules/fhir-from-10000-ft.qmd
            - modules/fhir-from-1000-ft.qmd
            - file: modules/fhir-research.qmd
              text: "Real World Research"
            - modules/fhir-history.qmd
            - modules/terminology.qmd
            - modules/cdms.qmd
            - file: modules/fhir-community.qmd
              text: Community & Documentation
            - modules/key-fhir-resources.qmd
            - file: modules/fhir-accessing-data.qmd
              text: Using the FHIR API
        - section: "SMART on FHIR"
          contents:
            - modules/smart-on-fhir-intro.qmd
            - modules/smart-on-fhir-tech.qmd
        - section: "Data Modeling in FHIR"
          contents:
            - file: modules/data-modeling-reading-igs.qmd
              text: Reading IGs
            - file: modules/data-modeling-real-world-igs.qmd
              text: Real World IGs
            - file: modules/data-modeling-writing-igs.qmd
              text: Writing IGs

    - id: working-with-data
      title: Working With Data
      style: floating
      search: false
      align: left
      collapse-level: 2
      contents:
        - file: sections/working-with-data.qmd
          text: Working With Data
        - section: "Tabular Analysis"
          contents:
            - file: modules/tabular-intro.qmd
              text: Introduction
            - file: modules/tabular-python.qmd
              text: Using Python
            - file: modules/tabular-r.qmd
              text: Using R
        - section: "REDCap With FHIR"
          contents:
            - modules/redcap-intro.qmd
            - modules/redcap-best-practices.qmd
            - modules/redcap-example.qmd

    - id: advanced-topics
      title: Advanced Topics
      style: floating
      search: false
      align: left
      collapse-level: 2
      contents:
        - file: sections/advanced-topics.qmd
          text: Advanced Topics
        - section: "Synthetic Data"
          contents:
            - modules/synthea-overview.qmd
            - modules/synthea-customizing.qmd
            - modules/synthea-test-server.qmd



  page-footer:
    center:
      - text: "&copy; 2023 The MITRE Corporation / <a href=\"https://github.com/mitre/fhir-for-research/README.md\">License information</a><br>Approved for Public Release / Case #23-0966"



format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    include-in-header: head.html
    include-after-body: scripts.html
