---
title: Accessing FHIR Data
area:
  name: Overview
topic:
  name: FHIR for Research
---

## Objectives

-   Understand how the standardized API that FHIR provides for accessing data supports interoperability.
-   See some simple examples of using the FHIR API.
-   Try modifying queries to a live FHIR server to see how the responses change.

## What is the FHIR API?

[Wikipedia](https://en.wikipedia.org/wiki/API) says:

> An application programming interface (API) is a way for two or more computer programs to communicate with each other.

[FHIR defines a standard API](https://www.hl7.org/fhir/http.html) that allows you (or your software) to request data from a FHIR-enabled server. The basics of this API should be consistent across FHIR servers, though servers can add their own custom functionality on top of the standard FHIR API.

FHIR's API is based on [an architecture called REST (REpresentational State Transfer)](https://www.ibm.com/topics/rest-apis). The details of this architecture are beyond the scope of this module, but we will cover a few high-level characteristics of REST below as they are important for understanding FHIR's API.

It's worth noting that most modern web-centric APIs are "RESTful" -- this makes it much easier for software engineers without prior FHIR experience to work with FHIR APIs because they have likely encountered other RESTful APIs.

## Constructing a FHIR API request

A FHIR server's API is typically accessed via a [URL](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL)[^1] like `https://hapi.fhir.org/baseR4/`.

[^1]: URLs may only be accessible inside an institution's firewall, or may be accessible to the public internet. Even if a FHIR server is accessible to the public internet, it may not respond to *any* request -- depending on how it is configured, it may require authentication (like a username and password) to return any data.

This URL is used to construct the API request, which typically takes the following form:

``` markdown
GET https://hapi.fhir.org/baseR4/Patient/1234
```

This would retrieve a FHIR instance of [Patient](https://www.hl7.org/fhir/patient.html) for the patient with the ID `1234`.

::: {.callout-note collapse="true"}
## Try a FHIR API request

The general structure of a FHIR API request includes the following:

-   `GET` = HTTP "verb", which tells the server whether you are asking for data or performing another operation (see [the FHIR documentation](https://www.hl7.org/fhir/http.html#trules) for details)
-   `https://hapi.fhir.org/baseR4/` = URL to the FHIR API
-   `Patient` = FHIR resource type you want
-   `1234` = The ID for the resource you want (note that an ID is not needed for some types of API requests)

The `https://hapi.fhir.org/baseR4` endpoint is a live FHIR server loaded with synthetic patient data. The patient ID `591702` exists in this data. Construct and run a FHIR query below to retrieve this patient's instance of Patient:

<!--# Proof of concept "run live query" widget is below -- this needs to get replaced with something much more robust that allows the user to construct the request themselves. -->

```{=html}
<div class="d-xl-flex row justify-content-around g-3">
  <div class="col-xl-4 mb-2 my-xl-auto mx-auto mx-xl-2" style="width:10rem;">
    <select id="accessing-fhir-data-query-http-verb" class="form-select" aria-label="Select a FHIR Resource" name="query-http-verb">
      <option selected>HTTP Verb</option>
      <option value="GET">GET</option>
      <option value="POST">POST</option>
      <option value="HEAD">HEAD</option>
      <option value="PATCH">PATCH</option>
      <option value="PUT">PUT</option>
      <option value="DELETE">DELETE</option>
    </select>
  </div>

  <div class="col-xl-4 mb-2 my-xl-auto">
    <div class="input-group">
      <input type="text" class="form-control form-control-sm" placeholder="URL to FHIR API" aria-label="URL to FHIR API" name="query-base-uri">

      <span class="input-group-text">/</span>

      <select id="accessing-fhir-data-query-resource" class="form-select form-select-sm" aria-label="Select a FHIR Resource" name="query-resource">
        <option selected>FHIR Resource</option>
        <option value="Patient">Patient</option>
        <option value="Observation">Observation</option>
      </select>

      <span class="input-group-text">/</span>

      <input type="text" class="form-control form-control-sm" placeholder="ID" aria-label="FHIR resource ID" name="query-id">
    </div>

  </div>

  <div class="col-xl-4 mb-2 my-xl-auto mx-2 text-center">
    <button class="btn btn-sm btn-primary rounded py-2 py-xl-1" style="line-height:1;" onclick="getPatient()">Run query</button>
  </div>
</div>

<br />

<div id="query-output"></div>
```

:::

The response to a FHIR API request is typically in [JSON](https://en.wikipedia.org/wiki/JSON) format, which, like REST, is a commonly used data interchange format.

Here's an example of what this looks like for an instance of a Patient resource:

<!--# Maybe do something like this for showing JSON? https://codepen.io/WartClaes/pen/QGGPJL -->

``` json
{
    "resourceType": "Patient",
    "id": "1234",
    "identifier":
    [
        {
            "use": "official",
            "type":
            {
                "coding":
                [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "smart-1032702"
        }
    ],
    "active": true,
    "name":
    [
        {
            "use": "official",
            "family": "Shaw",
            "given":
            [
                "Amy",
                "V"
            ]
        }
    ],
    "telecom":
    [
        {
            "system": "phone",
            "value": "800-782-6765",
            "use": "mobile"
        },
        {
            "system": "email",
            "value": "amy.shaw@example.com"
        }
    ],
    "gender": "female",
    "birthDate": "2007-03-20",
    "address":
    [
        {
            "use": "home",
            "line":
            [
                "49 Meadow St"
            ],
            "city": "Mounds",
            "state": "OK",
            "postalCode": "74047",
            "country": "USA"
        }
    ]
}
```

Modern programming languages universally support parsing JSON, which makes it easier to work with FHIR data than if a bespoke format was used.[^2] JSONlll also has the convenient property of being relatively easy for humans to read.

[^2]: FHIR servers can also typically return data in other standard formats, like [XML](https://en.wikipedia.org/wiki/XML).

```{=html}
<script>
  let getPatient = function() {
    let outputNode = document.getElementById('query-output');
    outputNode.innerHTML = ""; // clear any previous results

    let baseUriInput = document.querySelector("[name='query-base-uri']");
    let resourceInput = document.querySelector("[name='query-resource']");
    let idInput = document.querySelector("[name='query-id']");

    let method = document.querySelector("[name='query-http-verb']").value;


    // validate selected http verb
    if( method != "GET" ) {
      outputNode.innerHTML = `
        <div class="alert alert-danger">The FHIR query in this situation must be <b>GET</b>. Please try again.</div>
      `;
      return false;
    }


    // construct & validate full url
    if((baseUriInput.value == null) || (baseUriInput.value == "")) {
      outputNode.innerHTML = `
        <div class="alert alert-danger">The FHIR query base URI in this situation should be <b>https://hapi.fhir.org/baseR4</b>. Please try again.</div>
      `;
      return false;
    }
    if((resourceInput.value != "Patient") && (resourceInput.value != "Observation")) {
      outputNode.innerHTML = `
        <div class="alert alert-danger">The FHIR query base URI in this situation should be <b>Patient</b>. Please try again.</div>
      `;
      return false;
    }
    if((idInput.value == null) || (idInput.value == "")) {
      outputNode.innerHTML = `
        <div class="alert alert-danger">The FHIR query ID in this situation should be <b>591702</b>. Please try again.</div>
      `;
      return false;
    }
    let url = baseUriInput.value + "/" + resourceInput.value + "/" + idInput.value;


    // fetch request and construct response view
    fetch(url, {method: method})
    .then(res => res.text())
    .then(function (res) {
      let viewerString = jsonViewer(res, true);
      if( viewerString === null ) {
        outputNode.innerHTML = `
          <div class="alert alert-danger">
            FHIR query returned incorrect JSON syntax. Query response:
            <hr />
            ${res}
          </div>
        `
      }
      else {
        outputNode.innerHTML = `
          <div>
            <ul class="nav nav-tabs" id="outputTabs" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="outputViewerTab" data-bs-toggle="tab" data-bs-target="#outputViewer" type="button" role="tab" aria-controls="outputViewer" aria-selected="true">Viewer</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="outputJsonTab" data-bs-toggle="tab" data-bs-target="#outputJson" type="button" role="tab" aria-controls="outputJson" aria-selected="false">JSON</button>
              </li>
            </ul>
            <div class="tab-content" id="outputTabContent" style="height:50vh;overflow:scroll;">
              <div class="tab-pane fade show active" id="outputViewer" role="tabpanel" aria-labelledby="outputViewerTab"></div>
              <div class="tab-pane fade" id="outputJson" role="tabpanel" aria-labelledby="outputJsonTab"></div>
            </div>
          </div>
        `;
        document.querySelector("#outputViewer").appendChild( parseHTML( viewerString ) );
        document.querySelector("#outputJson").innerHTML = `
          <div class="sourceCode">
            <pre class="sourceCode json code-with-copy"><code class="sourceCode json">${res}</code></pre>
          </div>
        `;

      }
    })
    .catch(function(err) {
      // This is where you run code if the server returns any errors
      console.log("Failed to fetch patient: ", err)
      outputNode.innerHTML = `
        <div class="alert alert-danger">FHIR query failed. The correct FHIR query is <b>GET https://hapi.fhir.org/baseR4/Patient/591702</b>. Please try again.</div>
      `
    });

    return false;
  };
</script>
```
