---
title: "Module: History of FHIR"
author: "Blake Bergstrom"
format: html
editor: visual
toc: true
---

## Learning Objectives

-   Objective 1

-   Objective 2

-   ...

## 1. Evolution of HL7® Standards

HL7® has been developing standards for the **transfer of healthcare data** since the late 1980s, with three major standards being implemented since then. Each successive standard has been built on the lessons learned from the previous one, resulting in the current version of FHIR® today.

### 1.1 HL7® Version 2: Messages

Released in 1989, HL7® V2 allowed for the **simple transfer of messages** for clinical and patient care information. It was mainly **developed by clinical interface specialists** and is essentially a database query language that both developers can come up to speed quickly on and healthcare providers can use to send or request messages containing health data. The drawback of being so simple is that it does not support more complex interactions. It is currently the most widely used messaging standard in healthcare today, as it is the most mature.

### 1.2 HL7® Version 3: Clinical Documents

Released in 2005, HL7® V3 was created to address the challenges brought by the simplicity of HL7® V2. As opposed to clinical interface specialists, it was instead largely **influenced by government and healthcare information users**. In addition to just the simple transfer of messages, it specifies the **content of the data** **exchanged** between healthcare applications as well as **how the exchange is implemented** and managed. This data model was used in the developed of **HL7® Clinical Documentation Architecture (CDA)**, which is a framework for creating clinical documents.

This era of HL7® standards attempted to increase adoption yet ran into hurdles of its own:

1.  HL7® V3 is not backwards compatible with HL7® V2, meaning existing interfaces cannot communicate with its implementations
2.  HL7® V3 and HL7® CDA are very complex and not clearly specified, requiring significant onboarding for developers to understand

In response to these issues, HL7® V3 adoption has not been as large as HL7® V2, as it is primarily used in systems that either have never had HL7® V2 implementations or in areas with government enforcement of HL7® V3 usage.

### 1.3 FHIR®: Web Technologies

In the early 2010s, the scope of data sharing in the healthcare space needed to be broadened, going beyond simple messages and clinical documents to span organizations, disciplines, and borders. The expansion of mobile and cloud-based applications was slowly finding its way into the healthcare space and standards needed to keep up. Thus enters HL7® FHIR®, which is an alternative to document-centric approaches and leverages **web technologies such as HTTP-based RESTful APIs** to expand both the type of information that can be exchanged as well as the types of systems that can exchange it.

With a major goal being to facilitate interoperability between legacy health care systems, it both builds upon previous standards (HL7® V2, HL7® V3, HL7® CDA) as well as adopts modern web technologies. FHIR® has been able to bridge the gap between 30 year old standards and modern web-based connectivity. And with its focus away from specified messages/documents and more towards the use of small building blocks (Resources) to build implementations, it can be customized to fit much more use cases compared to its predecessors.

## 2. FHIR Eras

### 2.1 Era 1: Early Concepts

The basic concepts of FHIR® start with the beginnings of the internet in the mid 1990s. Web 1.0 was largely based on static pages using **HTTP (Hypertext Transfer Protocol)** to retrieve them. With such as limited system, **REST (REpresentational State Transfer)** was developed and popularized in the early 2000s. Its purpose was to create a standard framework for HTTP that could allow two servers to communicate and exchange data anywhere in the world, thus providing the structure for Web 2.0 and the explosion of worldwide websites in the 2000s.

At this point in time, healthcare data exchange was very limited to sending messages and documents and was not using any web-based transactional frameworks. Then in the late 2000s, the idea emerged to apply RESTful data exchange principles in healthcare within HL7® and its interoperability/web development partners. FHIR® was then officially introduced in 2012, beginning the era of healthcare API development and web-based health data exchange. Shortly after, support also came from the JASON task force, which is an independent group of elite scientists that has advised the government on matters of science and technology since the 1960s. In 2013, the [JASON Report titled "A Robust Health Data Infrastructure"](https://www.healthit.gov/sites/default/files/ptp13-700hhs_white.pdf) was published and called for health data APIs to be developed to liberate data that was locked in electronic health records. This helped pave the way for significant government support of FHIR® in the coming years.

### 2.2. Era 2: Developing the Core

### 2.3 Era 3: Acceleration

## 3. Government Help
