---
title: FHIR Community & Resources

area:
  name: Overview
topic:
  name: FHIR for Research

roles:
  - Informaticist
  - Software Engineer

learning_objectives:
  - question: "How can I get involved with the FHIR community?"
    answer: "You can interact with the FHIR community through [Work Groups](https://confluence.hl7.org/pages/viewpage.action?pageId=4489802), Zulip ([chat.fhir.org](chat.fhir.org)), and [Connectathons](https://confluence.hl7.org/display/FHIR/Connectathons)."
  - question: "Where can I ask FHIR related questions?"
    answer: "Zulip ([chat.fhir.org](https://chat.fhir.org)), the [FHIR Community Forum](http://community.fhir.org), and [StackOverflow](https://stackoverflow.com/questions/tagged/hl7_fhir) are great places to ask FHIR-related questions."
  - question: "Where can I find more information on HL7?"
    answer: "HL7 resources are primarily found in [HL7 Confluence](https://confluence.hl7.org) and project status can be seen in [HL7 Jira](https://jira.hl7.org/secure/Dashboard.jspa)."

---

## Introduction

FHIR has an active community of users who engage in discussions and offer advice. Discussions take place in a variety of forums.

This module will intoduce you to the HL7 and FHIR community, offer suggestions on where to ask questions, and clarify the various touchpoints and engagement opportunities.


## The HL7 FHIR community

The HL7 FHIR community is comprised of developers, maintainers, and implementers that engage with the [FHIR specification](https://hl7.org/fhir/). Community-members work in a variety of environments including clinical settings, health-focused companies and non-profits, and local, state, and federal health agencies. [HL7](<https://hl7.org>) <!--# FIX this link isn't valid Markdown syntax -- remove the < > —MM 3/15/23 11:43 AM -->manages the [FHIR standard](https://hl7.org/fhir/), FHIR technology (e.g., [ballotting and publishing implementation guides (IGs)](http://fhir.org/guides/registry/), and the [FHIR API](https://www.hl7.org/fhir/http.html)), and the community of maintainers and implementers. 

[FHIR](<https://hl7.org/fhir/>) is an open source specification, and the vast majority of HL7's FHIR work is done in public forums and channels. Any interested person can join in to discuss or contribute. The FHIR community also develops many [FHIR Implementation Guides (IGs)](http://fhir.org/guides/registry/) publicly. This approach makes members of the community accessible to other implementers and developers who want to ask questions, follow the progress of work, or contribute to the work via the channels described below.

### HL7 Work Groups

HL7 specifications and many FHIR Implementation Guides are developed as [HL7 Projects](http://www.hl7.org/special/Committees/projman/searchableProjectIndex.cfm?action=list). HL7 Projects include a variety of initiatives. For the purpose of this module, "HL7 Projects" refers to any efforts, including IGs, that are developed under the guidance of one or more [HL7 Work Groups](https://confluence.hl7.org/pages/viewpage.action?pageId=4489802). [Work Groups](https://confluence.hl7.org/pages/viewpage.action?pageId=4489802) are:

> ...the bodies within HL7 that take on responsibility for developing and maintaining standards. They are where the "work" of HL7 gets done. HL7 has a large number of work groups covering the spectrum of the healthcare space. All work groups are open to participation by anyone with an interest in their content.

Each Work Group lists the [projects under their umbrella](http://www.hl7.org/Special/committees/index.cfm?ref=nav).

Work Groups typically meet on a weekly basis for a [conference call](http://www.hl7.org/concalls/CallDirectory.aspx), as well as in-person or hybrid at [HL7 Working Group Meetings](https://www.hl7.org/events/workgroupmeetings.cfm?ref=nav), which are held three times per year.

HL7 Work Groups consist of subject matter experts and other stakeholders. Each Work Group has a [mailing list](https://confluence.hl7.org/display/FHIR/Mailing+List+Instructions) that you can join to communicate with the Work Group, including asking for time on an upcoming conference call. Work Groups also post conference call agendas on their Confluence sites (see the [Work Group directory](https://confluence.hl7.org/pages/viewpage.action?pageId=4489802) for Confluence links).

#### Getting started

The fastest way to get started is to join a regular [conference call](http://www.hl7.org/concalls/CallDirectory.aspx) and ask to introduce yourself. There is a core leadership team for each Work Group that facilitates meetings. Attendees vary depending on agenda content.

Alternatively (or additionally), join the Work Group's [mailing list](https://confluence.hl7.org/display/FHIR/Mailing+List+Instructions) and reach out to the group's leadership to introduce yourself. The mailing list is also used to request items be added to a future agenda. 

#### Tips for attending Work Group meetings:

- Get specific questions addressed by asking to be on the agenda ahead of the meeting.

- Be prepared to discuss your agenda item(s). Agendas are available ahead of the meeting on the Work Group's Confluence page.

- Share your expertise. Contributions to the Work Group ensure that new projects and specifications can be implemented and used by the community. That requires input from a variety of stakeholders.

### Zulip (chat.fhir.org)

Zulip ([chat.fhir.org](https://chat.fhir.org)) is an asynchronous communication platform, similar to Slack or Teams messaging. Anyone is welcome to join and it can be an valuable tool for asking questions and connecting with others that have similar objectives for health data. 

Zulip has Streams (like Channels on Slack) for general topics like [Implementation Guide development](https://chat.fhir.org/#narrow/stream/179252-IG-creation) and [Terminology](https://chat.fhir.org/#narrow/stream/179202-terminology), and and domain-specific topics like [Cancer Interoperability](https://chat.fhir.org/#narrow/stream/179234-Cancer-Interoperability). Users post comments or questions inside the Stream where others can respond. Streams can be found by searching for specific topics or browsing through the list. Searching all Streams or narrowing a search to a certain Stream in the search bar is helpful for troubleshooting common problems or seeing if anyone else has asked the same question before.

#### Getting started

Before using Zulip, review HL7's [community expectations](https://confluence.hl7.org/display/FHIR/Chat.fhir.org+Community+Expectations). 

If you have a question and don't know which Stream to post it in, the [#implementers](https://chat.fhir.org/#narrow/stream/179166-implementers) Stream is a good place to start. 

Other useful Streams to subscribe to include:

- [#Announcements](https://chat.fhir.org/#narrow/stream/179240-Announcements): posts with new Streams, releases of new versions of specifications, and ballot updates

- [#implementers](https://chat.fhir.org/#narrow/stream/179166-implementers): discussion about implementing FHIR resources

- [#analytics on FHIR](https://chat.fhir.org/#narrow/stream/179219-analytics-on-FHIR): useful for those using FHIR interfaces and APIs for data analytics

- [#social](https://chat.fhir.org/#narrow/stream/179160-social): general discussion about the FHIR community with the occasional fun update from a community member



### Connectathons

[Connectathons](https://confluence.hl7.org/display/FHIR/Connectathons) are an opportunity for contributors and community members to engage synchronously for discussions and interoperability testing. HL7 describes [Connectathons](https://confluence.hl7.org/display/FHIR/Connectathons) as:

> ...an event that is centered on developing the HL7 FHIR Specification including resources, profiles and implementation guides. The purpose of a Connectathon is to prove that the specification is complete and facilitate FHIR implementation guide maturity.

Three Connectathons are held each year in both in-person and virtual formats. Anyone can [attend as a participant](https://confluence.hl7.org/display/FHIR/Connectathons) or submit a proposal to be a [Track Lead](https://confluence.hl7.org/display/FHIR/Connectathon+Track+Lead+Responsibilities). Connectathon Track Leads share their specification or resource for implementers to test drive and offer feedback. A complete list of the Tracks is posted before the Connectathon, and offerings from [previous Connectathons](https://confluence.hl7.org/display/FHIR/Previous+Connectathons) can be browsed as well. 


#### Getting started

If you'd like to attend a Connectathon, you can find information about the upcoming Connectathons on [HL7's Connectathon events page](https://www.hl7.org/events/fhir-connectathon/) or the [Connectathon Confluence page](https://confluence.hl7.org/display/FHIR/Connectathons).

The [Connectathon FAQs](https://confluence.hl7.org/display/FHIR/HL7+FHIR+Connectathon+FAQs) provide information on requirements to participate. 

First time attendees must watch the [FHIR Training for Beginners Newcomer Orientation](https://vimeo.com/542197402/8fb80fea04).

Each Connectathon hosts a virtual Participant Information Session several weeks ahead of the Connectathon event. The Participant Information Session includes information about what Tracks are available, how to connect with Track Leads, and how to prepare your sandbox system. For an example of what to expect, a recording of the [January 2023 Connectathon Participant Information Session](https://www.youtube.com/watch?v=hA_cW2gG7wE) is available, as well as the [check lists](https://confluence.hl7.org/display/FHIR/2023+-+01+Connectathon+32) for attendees and Track Leads.

## HL7 FHIR resources

### HL7 Confluence

Documentation on HL7 processes and general information is typically found in the [HL7 Confluence](https://confluence.hl7.org) site. Confluence is a Wikipedia-like documentation website for HL7. Many of the links throughout this module go to HL7 Confluence pages. The site is useful for finding:

-   Relevant HL7 projects in development
-   Schedules and information for HL7 Work Groups
-   Processes and documentation for HL7 and FHIR infrastructure

The Confluence site also includes tips on [getting involved](https://confluence.hl7.org/display/FHIR/Getting+Involved) and [implementor support](https://confluence.hl7.org/display/FHIR/Implementer+Support).

### HL7 Jira

Project work and specification development primarily occurs in [HL7 Jira](https://jira.hl7.org/secure/Dashboard.jspa). The site is an issue-tracking resource used for managing comments and suggestions on HL7 specifications and terminologies. This includes the core FHIR specification and FHIR Implementation Guides developed with HL7 Work Group oversight.

### FHIR Community Forum

Discussion about FHIR implementation and development topics occurs in the [FHIR Community Forum](http://community.fhir.org/). The [FHIR Community Forum](http://community.fhir.org/t/welcome-to-the-fhir-community-forum/8) is a place to ask questions like:

> - How do I do [x]? where [x] is any kind of use of FHIR at all
> - Has anyone solved [my problem] with the specification? (or is anyone interested in this)
> - Why does FHIR work like it does?
> - What does everyone think about [making some change to the FHIR specification]?

Although the FHIR Community Forum is monitored, Zulip ([chat.fhir.org](https://chat.fhir.org)) may be more active.

### StackOverflow on FHIR
[StackOverflow](https://stackoverflow.com/) is a third-party forum for asking and answering technical questions. HL7 FHIR is one of the topics discussed on StackOverflow, in addition to many other technologies unrelated to health. Use the [hl7-fhir tag](https://stackoverflow.com/questions/tagged/hl7_fhir) for developer and programming questions about reference FHIR implementations.