---
title: Overview
sidebar: false
---

The **Overview** provides an introduction to FHIR for research, and details on two additional areas of general interest for researchers: SMART on FHIR and its research applications, and data modeling in FHIR.

Select your [role](/roles.html) to <mark>highlight</mark> the content that is most relevant to you:

<a href="#" data-role="investigator">Investigator</a> |
<a href="#" data-role="research-leader" class="fw-bold text-decoration-none"><mark>Research Leader</mark></a> |
<a href="#" data-role="informaticist">Informaticist</a> |
<a href="#" data-role="software-engineer">Software Engineer</a> |
<a href="#" data-role="clinician-scientist">Clinician Scientist/Trainee</a>

## FHIR for Research

-   <mark>[FHIR from 10,000 Feet](/modules/fhir-from-10000-ft.qmd)</mark>
-   [FHIR from 1,000 Feet](/modules/fhir-from-1000-ft.qmd)
-   <mark>[Real-World Research Using FHIR](/modules/fhir-research.qmd)</mark>
-   [Key FHIR Resources](/modules/10-intro--key-fhir-resources/index.html)
-   [Accessing FHIR Data High Level](/modules/10-intro--accessing-fhir-data/index.html)
-   [Brief History of FHIR](/modules/10-intro--brief-history-of-fhir/index.html)
-   [Terminology Introduction](/modules/10-intro--terminology-introduction/index.html)
-   [Common Data Models & FHIR](/modules/10-intro--common-data-models-and-fhir/index.html)
-   [The FHIR Community & Documentation](/modules/fhir-community.qmd)

## SMART on FHIR

-   [*FHIR from 10,000 feet*](/modules//index.html)
-   <mark>[SMART on FHIR high level overview](/modules/20-intro-smart-on-fhir--overview/index.html)</mark>
-   <mark>[Real-world research using SMART on FHIR](/modules/20-intro-smart-on-fhir--real-world-research/index.html)</mark>
-   [Technical quick start](/modules/20-intro-smart-on-fhir--technical-quick-start/index.html)

## Data Modeling in FHIR

-   [*FHIR from 10,000 feet*](/modules/fhir-from-10000-ft.qmd)
-   [*Key FHIR Resources*](/modules/10-intro--key-fhir-resources/index.html)
-   [*Terminology Introduction*](/modules/10-intro--key-fhir-resources/index.html)
-   <mark>[Real world FHIR specifications](/modules/30-fhir-data-modeling--real-world-ig/index.html)</mark>
-   [Reading a FHIR specification](/modules/30-fhir-data-modeling--reading-ig/index.html)
-   [*Terminology Introduction*](/modules/10-intro--terminology-introduction/index.html)
-   [Writing a FHIR specification](/modules/30-fhir-data-modeling--writing-ig/index.html)
-   [API-focused FHIR Resources](/modules/30-fhir-data-modeling--api-focused-fhir-resources/index.html)


<script>

/* constant variable role_module_map: array<object> [
 *   {
 *     role: string
 *     modules: array<string> (substring of each html link such that it uniquely identifies a module)
 *   }
 * ]
 *
 * TODO: ideally extract this from each qmd file's frontmatter, or define this in one json file and let each file build off of it
 *
 */
const role_module_map = [
  {
    role: "investigator",
    modules: ["fhir-from-10000-ft", "history-of-fhir", "terminology-introduction", "common-data-models", "fhir-community", "smart-on-fhir--overview",  "reading-ig"]
  },
  {
    role: "research-leader",
    modules: ["fhir-from-10000-ft", "fhir-from-1000-ft", "fhir-research", "terminology-introduction", "fhir-community", "reading-ig", "writing-ig", "api-focused-fhir-resources"]
  },
  {
    role: "informaticist",
    modules: ["fhir-from-10000-ft", "fhir-from-1000-ft", "fhir-research", "key-fhir-resources", "terminology-introduction", "common-data-models", "fhir-community", "smart-on-fhir--overview", "smart-on-fhir--real-world"]
  },
  {
    role: "software-engineer",
    modules: ["fhir-from-10000-ft", "fhir-from-1000-ft", "key-fhir-resources", "terminology-introduction", "smart-on-fhir--overview", "smart-on-fhir--technical", "reading-ig", "writing-ig", "api-focused-fhir-resources"]
  },
  {
    role: "clinician-scientist",
    modules: ["fhir-from-10000-ft", "fhir-from-1000-ft", "fhir-research", "key-fhir-resources", "history-of-fhir", "terminology-introduction", "common-data-models", "fhir-community", "smart-on-fhir--overview", "smart-on-fhir--real-world", "smart-on-fhir--technical", "reading-ig", "writing-ig", "api-focused-fhir-resources"]
  }
]

const all_modules = document.querySelectorAll("section>ul>li");

/* select_modules(string)
 *   highlights modules corresponding to role via role_module_map
 *   param: string - role name in lower kebab case
 */
function select_modules(string) {
    // remove all highlights
    all_modules.forEach((li_node) => {
        //console.log("removing highlight for ", li_node);

        var mark_node = li_node.firstChild;
        var a_node = mark_node.firstChild;

        if( mark_node.nodeName == "MARK" ) {
            li_node.removeChild(mark_node);
            li_node.appendChild(a_node);
        }
    });

    // add highlights based on role_module_map
    role_module_map.forEach((mapping) => {
        if( mapping.role == string ) {
            mapping.modules.forEach((interest_module) => {
                document.querySelectorAll(`[href*="${interest_module}"]`).forEach((interest_a_node) => {

                    //console.log("selecting module ", interest_a_node);

                    var interest_li_node = interest_a_node.parentNode;
                    var mark_node = document.createElement("mark");
                    interest_li_node.appendChild(mark_node);
                    mark_node.appendChild(interest_a_node);

                    //console.log("appended ", interest_a_node, " to ", mark_node);
                });
            });
            return;
        }
    })
}


/* select_role(string)
 *   clears any previous selected roles
 *   highlights the selected role
 */
function select_role(string) {
    document.querySelectorAll("[data-role]").forEach((a_node) => {
        a_node.classList.remove("fw-bold");
        a_node.classList.remove("text-decoration-none");

        var mark_node = a_node.firstChild;
        var text_node = mark_node.firstChild;

        if( mark_node.nodeName == "MARK" ) {
            a_node.removeChild(mark_node);
            a_node.appendChild(text_node);
        }
    });

    var selected_a_node = document.querySelector(`[data-role="${string}"]`);
    selected_a_node.classList.add("fw-bold");
    selected_a_node.classList.add("text-decoration-none");

    var text_node = selected_a_node.firstChild;
    var mark_node = document.createElement("mark");

    selected_a_node.appendChild(mark_node);
    mark_node.appendChild(text_node);
}


// trigger role selection on clicking <a data-role=...>
document.querySelectorAll("a[data-role]").forEach((role_link) => {
    role_link.addEventListener("click", (e) => {
        var role = e.target.dataset.role;
        select_role(role);
        select_modules(role);
    });
});

</script>
