---
title: Working with FHIR Data
sidebar: false
---

**Working with FHIR Data** covers approaches to gathering and analyzing FHIR-formatted data for research purposes.

Select your [role](/roles.html) to <mark>highlight</mark> the content that is most relevant to you:

<a href="#">Investigator</a> |
<a href="#">Research Leader</a> |
<a href="#">Informaticist</a> |
<a href="#">Software Engineer</a> |
<a href="#">Clinician Scientist/Trainee</a>

## Tabular Analysis

-   *Recommended: complete highlighted [FHIR for Research](overview.qmd) modules for your role first*
-   [Introduction to Analyzing FHIR Data in a Tabular Format](/modules/tabular-intro.qmd)
-   [Analyzing FHIR Data in a Tabular Format With R](/modules/tabular-r.qmd)
-   [Analyzing FHIR Data in a Tabular Format With Python](/modules/tabular-python.qmd)

## REDCap

-   *Recommended: complete highlighted [FHIR for Research](overview.qmd) modules for your role first*
-   [Introduction](/modules/redcap-intro.qmd)
-   [REDCap on FHIR](/modules/redcap-fhir.qmd)