---
title: "Module: Real World Research Using FHIR"

area:
  name: Overview
topic:
  name: FHIR for Research
  
roles:
  - Investigator
  - Research Leaders
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee
  
learning_objectives:
  - question: What are the key ways FHIR has previosuly been used in research?
    answer: tbd
  - question: What are examples of FHIR's use in research that may be applicable to your work?
---

FHIR has been adopted in many clinical settings, but its utilization in research has been slower. There are several ways FHIR could be beneficial to research though, including data-sharing, researcher and participant communication, and institutional collaboration.

## Research themes

A review of studies that use FHIR in their research, including a meta-analysis of papers on FHIR for research [@duda2022], found four common themes of research that utilizes FHIR:

### **Data models and platforms**

As a standard for exchanging data, FHIR has been used in several studies to transform health data from different data models into an interoperable format. This is a common issue for studies or research that uses data from different sites, agencies, and sources.

<!--# DISCUSS: The CTR's in particular will be familiar with this information but thought it might be helpful framing and level-setting if they're not familiar --KMB-->

<!--# FIX: Note that this might have overlap with the CDMs & FHIR section. Please coordiante. --MM -->

Common Data Models (CDMs) and platforms that have been used with FHIR in research include:

-   [Observational Medical Outcomes partnership (OMOP)](https://www.ohdsi.org/data-standardization/), a CDM for standardizing both administrative and electronic health record (EHR). It was developed by the Observational Health Data Sciences and Informatics (OHDSI) initiative, and has been used by researchers, healthcare workers, analysts, etc.

-   There is an [OMOPonFHIR](https://omoponfhir.org) initiative led by Georgia Tech to map between OMOP and FHIR

-   [PCORnet](https://pcornet.org/data/) is another CDM, containing clinical data, patient-reported outcomes, and payor data, with the intent to support multi-site research.

-   [openEHR](https://www.openehr.org/about_us) is an EHR platform that includes modelling tools and clinical knowledge management (CKM).

-   [Research Electronic Data Capture (REDCap)](https://www.project-redcap.org) is a HIPAA compliant tool for managing online surveys and databases, commonly used by health researchers.

Examples:

-   In "Automated production of research data marts from a canonical fast healthcare interoperability resource data repository: applications to COVID-19 research," [@Lenert_Ilatovskiy_Agnew_Rudisill_Jacobs_Weatherston_Deans_Jr_2021] uses FHIR for rapid exchange of COVID-19 data and then transforms it to PCORnet and OMOP.

-   In "ASH Research Collaborative: a real-world data infrastructure to support real-world evidence development and learning healthcare systems in hematology,"[@Wood_Marks_Plovnick_Hewitt_Neuberg_Walters_Dolan_Tucker_Abrams_Thompson_etal._2021] uses real-world data, OMOP, and FHIR to generate disease-specific learning communities.

-   In "From OpenEHR to FHIR and OMOP data model for microbiology findings" [@Rinaldi_Thun_2021], illustrates the process of collecting data from eight institutions, converting it from openEHR to FHIR-format, and then from the FHIR-format to OMOP to support different use cases while maintaining interoperability.

-   In "REDCap on FHIR: Clinical Data Interoperability Services," [@Cheng_Duda_Taylor_Delacqua_Lewis_Bosler_Johnson_Harris_2021] developed the Clinical Data Interoperability Services to exhcange data between REDCap and any EHR with the FHIR API.

### **SMART on FHIR**

[SMART on FHIR](https://smarthealthit.org/about-smart-2/) is an application programming interface (API) that enables interoperability between applications and any healthcare system with a FHIR-enabled EHR. A widely used implementation of SMART on FHIR is the Apple Health Records API, which allows iPhone users to request records from EHRs and other health systems, and then store those health records on their device.

SMART has an [app gallery](https://apps.smarthealthit.org/apps?sort=name-asc) for viewing developers' applications that can be implemented in an EHR.

An example of SMART on FHIR in a research context is "Evolving Research Data Sharing Networks to Clinical App Sharing Networks" [@Wagholikar_Jain_Oliveira_Mandel_Klann_Colas_Patil_Yadav_Mandl_Carton_etal._2017], trialed multi-site app sharing for shared decision-making between two different institutions using four SMART-on-FHIR apps.

<!--# FIX: Link to SMART on FHIR topic. --MM -->

### **Patient-facing apps**

FHIR can also be used to create interoperable, patient-facing apps that can support research, either through data collection or facilitating research-participant communication. Some apps listed in the SMART app gallery linked above are patient-facing apps.

Example: "C3-PRO: Connecting ResearchKit to the Health System Using i2b2 and FHIR" [@Pfiffner_Pinyol_Natter_Mandl_2016], uses FHIR to facilitate the process and record-keeping of patient consent, health data, and patient-reported outcomes during the research process.

### **Multi-site research**

Multi-site data-sharing requires standardized formats and common terminologies, which can be facilitated by FHIR. A larger pool of data from multiple healthcare institutions can mean more comprehensive studies or broader groups of patients to draw from for research participation.

Examples:

-   "The Architecture of a Feasibility Query Portal for Distributed COVID-19 Fast Healthcare Interoperability Resources (FHIR) Patient Data Repositories: Design and Implementation Study" [@Gruendner_Deppenwiese_Folz_Köhler_Kroll_Prokosch_Rosenau_Rühle_Scheidl_Schüttler_etal._2022], describes the process of querying data, compiling in FHIR-format, and distributing to multiple hospitals for improved data accessibility.

## 
