on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

# Allow only one concurrent deployment
# But do not cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries
        uses: r-lib/actions/setup-renv@v2
        # includes dependency cache

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # cache pip dependencies
        run: pip install -r requirements.txt

      - name: Render Quarto
        run: quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2
