on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

# Allow only one concurrent deployment
# But do not cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries
        uses: r-lib/actions/setup-renv@v2
        # includes dependency cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # cache pip dependencies

      - name: Install Python libraries
        run: pip install -r requirements.txt

      - name: Render Quarto
        run: quarto render

      - name: Remove .html extensions
        run: |
          # Find all HTML files in the current directory and its subdirectories
          HTML_FILES=$(find . -type f -name "*.html")

          # Loop through each HTML file
          for file in $HTML_FILES; do
              # Replace .html extension from <a> tags with empty string for relative links only
              sed -i 's/\(<a[^>]*href="\)\([^:"]*\)\.html\("[^>]*>\)/\1\2\3/g' $file
          done

          echo "HTML files processed successfully!"

      # Work around https://github.com/quarto-dev/quarto-cli/issues/3892
      - name: Manually copy over MP4 files
        run: |
          cp modules/images/*.mp4 public/modules/images/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2
